version: '3.9'
services:
  frontend:
    build: ./application/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./application/frontend:/app
    depends_on:
      - backend

  backend:
    build: ./application/backend
    ports:
      - "3001:3001"
    volumes:
      - ./application/backend:/app
    environment:
      - PORT=3001
      - MONGO_DB=app_db
      - MONGO_TEST_DB=app_db_test
      - MONGO_URI=db:27017
      - MONGO_ATLAS=${MONGO_ATLAS}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - USER_MAILER_USER=${USER_MAILER_USER}
      - USER_MAILER_PASSWORD=${USER_MAILER_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URI=${REDIS_URI}
    depends_on:
      - db
      - redis
      # - kafka

  db:
    image: mongo:7.0.3
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # kafka:
  #   image: landoop/fast-data-dev:latest
  #   ports:
  #     - "3030:3030" # Web UI
  #     - "8081:8081" # Schema registry
  #     - "8082:8082" # Kafka REST proxy
  #     - "8083:8083" # Kafka connect distributed
  #     - "9092:9092" # Kafka broker
  #     - "2181:2181" # ZooKeeper
  #   environment:
  #     ADV_HOST: 127.0.0.1
  #     RUNTESTS: 0
  #     DEBUG: 1
  #     SAMPLEDATA: 0

  nginx:
    build: ./nginx
    ports:
      - "80:80"
